### PR TITLE
Fix example rendering bug (closes #17)

### LINKED ISSUE #17: Example rendering bug
1) open any documentation entry with `@example`
2) open any other documentation entry with `@example`
3) `@example` of the first entry is shown instead of `@example` of the second
4) open documentation entry without `@example` to reset shown example

### PR DESCRIPTION
**Pull request by LeshaKoss**

### CODE REVIEW

File: ui/_lib/code/index.jsx [hunk 1]
```diff
@@ -15,14 +15,19 @@ export default class Code extends React.Component {
     }, this.props.options))
   }
 
+  componentWillReceiveProps(nextProps) {
+    this._codeMirror.setValue(nextProps.value)
+  }
```
Comment (kossnocorp) [inline ui/_lib/code/index.jsx]: Please check if value is actually changed and only then set it.

File: ui/_lib/code/index.jsx [hunk 2]
```diff
@@ -15,14 +15,19 @@ export default class Code extends React.Component {
...
   componentWillUnmount() {
     this._codeMirror.toTextArea()
   }
 
   render() {
     return <textarea
-      defaultValue={this.props.value}
+      value={this.props.value}
       ref='textarea'
+      readOnly
```
Comment (kossnocorp) [inline ui/_lib/code/index.jsx]: Is it really necessary? Why `setValue` is not enough?

Comment (LeshaKoss) [inline ui/_lib/code/index.jsx]: No, it's not necessary, I will change back right away
